- name: Check Number
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: enter number
    private: no
  tasks:
  - name: greater number
    ansible.builtin.debug:
     msg: "nmuber {{number}} is greterthan 10"
    when: number | int > 10