- name: default values
  hosts: localhost
  tasks:
  - name: default
    ansible.builtin.debug:
     msg: "this is {{course | default('ansible') }}"

- name: Upper values
  hosts: localhost
  vars:
    greetings: "hi good morning"
  tasks:
  - name: upper
    ansible.builtin.debug:
     msg: "this is {{greetings | upper }}"

- name: Unique values
  hosts: localhost
  vars:
    list: [1, 2, 2, 3, 3]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{list | unique}}"

- name: min max
  hosts: localhost
  vars:
    ages: [22, 23, 43, 44]
  tasks:
  - name: min and max ages
    ansible.builtin.debug:
      msg: "min age is {{ages | min}} and max age is {{ ages| max}}"

- name: dict to items
  hosts: localhost
  vars:
    mydict:
      course: devops
      duration: 120 hrs
  tasks:
  - name: before dict to items
    ansible.builtin.debug:
      msg: "{{mydict}}"
  - name: after dict to items
    ansible.builtin.debug:
      msg: "{{mydict | dict2items}}"

 