- name: Variables
  hosts: localhost
  Vars:
    Course: "Devops"
    Trainer: "Baji"
    Duration: "120hrs"
  tasks:
  - name: Print Info
    ansible.builtin.debug:
      msg: "i am a=learning{{Course}}from {{Trainer}} and duration {{Duration}}"
