- name: Variables
  hosts: localhost
  vars:
    Course: "Terraform"
    Trainer: "Baji"
    Duration: "120hrs"
  tasks:
    Course: "DevOps"
    Trainer: "Baji"
    Duration: "120hrs"
    ansible.builtin.debug:
      msg: "i am a=learning{{Course}}from {{Trainer}} and duration {{Duration}}"