- name: Variables
  hosts: localhost
  vars:
    Course: "Terraform"
    Trainer: "Baji"
    Duration: "120hrs"
  tasks:
  - name: Print Info to override
    vars:
      Course: "DevOps"
      Trainer: "Baji"
      Duration: "120hrs"
    ansible.builtin.debug:
       msg: "i am learning {{Course}} from {{Trainer}} and duration {{Duration}}"
  - name: normal
    ansible.builtin.debug:
      msg: "i am learning {{Course}} from {{Trainer}} and duration {{Duration}}"